language: python

addons:
  postgresql: "9.4"

sudo: required

before_script:
  - printf "[pg_qgep]\nhost=localhost\ndbname=qgep\nuser=postgres" > ~/.pg_service.conf
  - psql -c 'CREATE DATABASE qgep;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d qgep
  - psql -c 'CREATE EXTENSION hstore;' -U postgres -d qgep

script: $TRAVIS_BUILD_DIR/scripts/db_setup.sh
